Repository goorm4-A/WooriGa-BE, pull requests merged in 2025-06, with the labels that each got.

#27 [Feat] 로그인 후 유저 정보 조회/수정
  src/main/generated/com/example/server/domain/entity/QUser.java
  src/main/java/com/example/server/controller/LoginContoller.java
  src/main/java/com/example/server/controller/UserController.java
  src/main/java/com/example/server/converter/UserConverter.java
  src/main/java/com/example/server/domain/entity/User.java
  src/main/java/com/example/server/domain/enums/UserStatus.java
  src/main/java/com/example/server/dto/FamilyDTO.java
  src/main/java/com/example/server/dto/FamilyInfoResponse.java
  src/main/java/com/example/server/dto/LoginDTO.java
  src/main/java/com/example/server/dto/UserDTO.java
  src/main/java/com/example/server/dto/user/LoginResponse.java
  src/main/java/com/example/server/dto/user/UserInfoRequest.java
  src/main/java/com/example/server/dto/user/UserInfoResponse.java
  src/main/java/com/example/server/global/status/SuccessStatus.java
  src/main/java/com/example/server/service/login/LoginService.java
  src/main/java/com/example/server/service/user/UserService.java
Labels: :sparkles: Feature

#28 [Feat] 회원 관련 API 개발
  src/main/generated/com/example/server/domain/entity/QUser.java
  src/main/java/com/example/server/ServerApplication.java
  src/main/java/com/example/server/controller/UserController.java
  src/main/java/com/example/server/converter/UserConverter.java
  src/main/java/com/example/server/domain/entity/User.java
  src/main/java/com/example/server/dto/user/UserInfoRequest.java
  src/main/java/com/example/server/dto/user/UserInfoResponse.java
  src/main/java/com/example/server/repository/UserRepository.java
  src/main/java/com/example/server/service/login/LoginService.java
  src/main/java/com/example/server/service/user/UserService.java
Labels: :sparkles: Feature

#35 [Feat] 가족 관련 기능 구현
  src/main/generated/com/example/server/domain/entity/QFamilyMember.java
  src/main/java/com/example/server/controller/FamilyMemberController.java
  src/main/java/com/example/server/controller/UserController.java
  src/main/java/com/example/server/converter/FamilyConverter.java
  src/main/java/com/example/server/domain/entity/Family.java
  src/main/java/com/example/server/domain/entity/FamilyMember.java
  src/main/java/com/example/server/dto/member/FamilyGroupDetailResponse.java
  src/main/java/com/example/server/dto/member/FamilyGroupResponse.java
  src/main/java/com/example/server/dto/member/FamilyMemberResponse.java
  src/main/java/com/example/server/dto/member/FamilyResponse.java
  src/main/java/com/example/server/repository/FamilyMemberRepository.java
  src/main/java/com/example/server/repository/FamilyRepository.java
  src/main/java/com/example/server/service/S3Service.java
  src/main/java/com/example/server/service/member/FamilyMemberService.java
  src/main/java/com/example/server/service/user/UserService.java
Labels: :sparkles: Feature

#36 [Feat] 가족 그룹 관련 기능
  src/main/java/com/example/server/controller/FamilyGroupController.java
  src/main/java/com/example/server/controller/FamilyMemberController.java
  src/main/java/com/example/server/controller/UserController.java
  src/main/java/com/example/server/converter/FamilyConverter.java
  src/main/java/com/example/server/domain/entity/Family.java
  src/main/java/com/example/server/domain/entity/FamilyMember.java
  src/main/java/com/example/server/dto/member/FamilyMemberDetailResponse.java
  src/main/java/com/example/server/global/status/ErrorStatus.java
  src/main/java/com/example/server/global/status/SuccessStatus.java
  src/main/java/com/example/server/service/family/FamilyGroupService.java
  src/main/java/com/example/server/service/family/FamilyMemberService.java
Labels: :sparkles: Feature

#38 fix: AnniversaryType 한글로 리턴
  src/main/java/com/example/server/dto/anniversary/AnniversaryResponseList.java
Labels: 🔨 Refactor

#53 [Fix] 그룹 조회 응답 형식 재수정
  src/main/java/com/example/server/converter/FamilyConverter.java
  src/main/java/com/example/server/dto/member/FamilyGroupResponse.java
  src/main/java/com/example/server/dto/member/FamilyNotPositionResponse.java
Labels: 🐞 BugFix, 📃 Docs

#54 [FIX] 최신 등록된 가족 그룹 이미지 방어 코드 설정
  src/main/java/com/example/server/converter/UserConverter.java
  src/main/java/com/example/server/service/user/UserService.java
Labels: 🐞 BugFix, 📃 Docs
